from core.brain import indexes
from tests.brain.conftest import make_env_note, make_note


def test_rebuild_writes_all_indexes(brain):
    make_note(brain, "wiki/tools/vol.md", "Volatility", type="tool",
              tags="volatility", tools="volatility", related='"[[plaso]]"')
    make_note(brain, "wiki/tools/plaso.md", "Plaso", type="tool",
              tags="plaso, timeline", cases="nitroba")
    summary = indexes.rebuild()
    assert summary["indexed"] == 2
    for name in indexes.INDEX_FILES:
        assert (brain / "indexes" / name).is_file()
    tag_index = (brain / "indexes" / "tag-index.md").read_text()
    assert "volatility" in tag_index and "Plaso" in tag_index
    case_index = (brain / "indexes" / "case-index.md").read_text()
    assert "nitroba" in case_index


def test_confidential_excluded_by_default(brain):
    make_note(brain, "wiki/tools/pub.md", "Public", type="tool", tags="x")
    make_note(brain, "wiki/tools/conf.md", "Sensitive", type="tool",
              tags="x", classification="confidential")
    summary = indexes.rebuild()
    assert summary["indexed"] == 1
    assert summary["skipped_confidential"] == 1
    assert "Sensitive" not in (brain / "indexes" / "tag-index.md").read_text()
    summary = indexes.rebuild(include_confidential=True)
    assert summary["indexed"] == 2


def test_secret_bearing_note_refused_without_value(brain):
    make_note(brain, "inbox/raw/bad.md", "Bad", body="password=supersecret")
    summary = indexes.rebuild()
    assert summary["skipped_secrets"] == 1
    warning = [w for w in summary["warnings"] if "SECRET-LIKE" in w][0]
    assert "bad.md" in warning and "supersecret" not in warning
    assert "supersecret" not in (brain / "indexes" / "tag-index.md").read_text()


def test_detects_broken_links_and_orphans(brain):
    make_note(brain, "wiki/concepts/a.md", "A", type="concept",
              tags="t", related='"[[nonexistent]]"')
    make_note(brain, "wiki/concepts/lonely.md", "Lonely", type="concept", tags="t")
    summary = indexes.rebuild()
    assert any("broken link [[nonexistent]]" in w for w in summary["warnings"])
    assert any("orphan" in w and "lonely" in w for w in summary["warnings"])


def test_environment_lint_warnings(brain):
    make_env_note(brain, "acme-corp", "Stale topology",
                  last_verified="2020-01-01", tags="acme-corp")
    make_env_note(brain, "acme-corp", "Verdict drift", tags="acme-corp",
                  body="Last time the attacker used a backdoor here.")
    make_env_note(brain, "acme-corp", "Run sourced", tags="acme-corp",
                  source_type="agent_run")
    make_env_note(brain, "other-corp", "Misfiled", tags="other",
                  rel="wiki/environments/acme-corp/misfiled.md")
    summary = indexes.rebuild()
    warnings = summary["warnings"]
    assert any("stale environment baseline" in w and "stale-topology" in w
               for w in warnings)
    assert any("verdict language" in w and "verdict-drift" in w
               for w in warnings)
    assert any("source.type 'agent_run' not allowed" in w and "run-sourced" in w
               for w in warnings)
    assert any("does not match its directory" in w and "misfiled" in w
               for w in warnings)


def test_environment_clean_note_no_env_warnings(brain, monkeypatch):
    import datetime as dt
    today = dt.date.today().isoformat()
    make_env_note(brain, "acme-corp", "Clean baseline", tags="acme-corp",
                  last_verified=today,
                  body="DC01/DC02 are domain controllers; admins use JUMP01.")
    summary = indexes.rebuild()
    env_warnings = [w for w in summary["warnings"]
                    if "clean-baseline" in w and "environment" in w]
    assert env_warnings == []


def test_rebuild_is_deterministic(brain):
    """Rebuilding with unchanged notes must be byte-identical — no wall-clock
    timestamps — so committed indexes never show spurious git diffs."""
    make_note(brain, "wiki/tools/vol.md", "Volatility", type="tool",
              tags="volatility", related='"[[plaso]]"')
    make_note(brain, "wiki/tools/plaso.md", "Plaso", type="tool",
              tags="plaso", cases="nitroba")
    indexes.rebuild()
    first = {name: (brain / "indexes" / name).read_bytes()
             for name in indexes.INDEX_FILES}
    indexes.rebuild()
    for name in indexes.INDEX_FILES:
        assert (brain / "indexes" / name).read_bytes() == first[name]
    header = (brain / "indexes" / "tag-index.md").read_text().splitlines()[2]
    assert header == "_Generated by rebuild_indexes — do not edit._"
