"""The system baseline: what every Windows installation in evidence states
about itself, read once from its hives and recorded as observations.

Two of three runs parsed the machine hives and never stated the operating
system, the time zone or the accounts; the report then carried "timestamps
rendered as recorded" instead of the time basis, and the analyst re-derived
facts a five-second read had already produced. The baseline runs after a
volume is mounted (or a collected tree is inventoried), once per
installation, through the same RECmd wrapper the analyst uses, with a
targeted batch (``share/.common/atlas_baseline.reb``), and writes one
profile per installation under ``analysis/baseline/``:

* os: product, build, service pack, edition, install date (on Windows 10
  and later the last feature update), registered owner and organisation
  (text typed at setup, not an identity);
* time: the zone key and biases and the time basis of each evidence class;
* identity: computer name, DNS suffix (only that), the LSA primary domain
  and its SID (decoded from the raw SECURITY values);
* accounts: the local SAM accounts (local only) and the profile list;
* interfaces: addresses, DHCP and leases per adapter, network profiles, the
  gateway MAC (the gateway's, never the host's);
* usb: USBSTOR devices with their serials; software: the uninstall entries;
* power: the last shutdown; settings: prefetcher, last-access updates,
  event log sizes and retention, shadow copies, the audit policy;
* hive_state: whether each hive was dirty and whether its logs were
  replayed; a dirty hive without logs lowers the confidence of its facts.

Values are read under the control set ``Select\\Current`` names; rows RECmd
recovered as deleted are skipped. Facts are observations (readings), never
findings: the report renders them under Scope and Evidence, the tasks may
cite them, the indicator catalog and the pivots leave them alone.
"""
from __future__ import annotations

import csv
import datetime as _dt
import json
import os
import re
import struct
from pathlib import Path
from typing import Any, Optional

HIVES = ("SYSTEM", "SOFTWARE", "SAM", "SECURITY")
BATCH = Path(__file__).resolve().parents[1] / "share" / ".common" / "atlas_baseline.reb"
OUT_DIR = "analysis/baseline"
PROFILE_ROOTS = ("Users", "Documents and Settings")
_CONFIG_TAIL = ("windows", "system32", "config")
_DIRTY_RE = re.compile(r"(?i)dirty|transaction log|replay")
_SAM_USER_RE = re.compile(r"Username:\s*(.+?)\s+Id:\s*(\d+)")
_SAM_DATES_RE = re.compile(r"Created:\s*([\d-]+ [\d:.]+)?\s*Last login:\s*([\d-]+ [\d:.]+)?")
_UNINSTALL_RE = re.compile(r"DisplayName:\s*(.*?)\s*DisplayVersion:\s*(.*?)\s*Publisher:\s*(.*?)(?:\s*InstallDate:\s*(\S*))?\s*$")
# The time zone plugin can print the key name with a duplicated tail; the
# name ends at its first "Time" word ("W. Europe Standard Time").
_ZONE_NAME_RE = re.compile(r"^(.*?\bTime)\b")
_PROFILE_RE = re.compile(r"KeyName:\s*(S-[\d-]+)")
_USB_RE = re.compile(r"(?i)USBSTOR\\([^\\]+)\\([^\\]+)")


def _usb_entry(key_path: str) -> Optional[tuple[str, str, str]]:
    """``(device, serial, note)`` from a USBSTOR key path. A device's own
    serial ends at the first "&"; an instance id Windows generated
    ("7&2a8b5f7c&0", "&" second) carries no serial and is kept whole."""
    m = _USB_RE.search(key_path or "")
    if not m:
        return None
    device, instance = m.group(1), m.group(2)
    if instance[1:2] == "&":
        return device, instance, "generated by Windows, the device reports no serial"
    return device, instance.split("&")[0], ""


# ── installations ────────────────────────────────────────────────────────

def _find_config_dirs(root: Path, max_depth: int = 5) -> list[tuple[Path, bool]]:
    """``(config dir, previous)`` for every ``Windows/System32/config`` that
    holds a SYSTEM hive under ``root``; a ``Windows.old`` tree is marked
    as a previous installation."""
    out: list[tuple[Path, bool]] = []
    stack: list[tuple[Path, int]] = [(root, 0)]
    while stack:
        here, depth = stack.pop()
        try:
            entries = [e for e in os.scandir(here) if e.is_dir(follow_symlinks=False)]
        except OSError:
            continue
        for e in entries:
            low = e.name.casefold()
            if low == "config" and here.name.casefold() == "system32" and here.parent.name.casefold() in ("windows", "winnt"):
                if any(f.casefold() == "system" for f in os.listdir(e.path) if os.path.isfile(os.path.join(e.path, f))):
                    previous = any(p.casefold() == "windows.old" for p in Path(e.path).parts)
                    out.append((Path(e.path), previous))
                continue
            if depth < max_depth and low not in ("mnt", ".atlas", "analysis", "exports", "reports", "$recycle.bin", "programdata"):
                stack.append((Path(e.path), depth + 1))
    return out


def _hives(config_dir: Path) -> dict[str, str]:
    names = {f.casefold(): f for f in os.listdir(config_dir) if os.path.isfile(config_dir / f)}
    return {h: str(config_dir / names[h.casefold()]) for h in HIVES if h.casefold() in names}


def find_installations(case_dir: str | os.PathLike) -> list[dict[str, Any]]:
    """Every Windows installation under a live mount or a collected tree."""
    root = Path(case_dir).resolve()
    out: list[dict[str, Any]] = []
    seen: set[str] = set()
    try:
        from core.mount_plan import mounted_volumes
        volumes = mounted_volumes(root)
    except Exception:  # noqa: BLE001
        volumes = []
    for vol in volumes:
        mp = vol.get("mount_point")
        if not mp:
            continue
        for cfg, previous in _find_config_dirs(Path(mp), max_depth=3):
            key = str(cfg)
            if key in seen:
                continue
            seen.add(key)
            stem = str(vol.get("stem") or Path(mp).parent.name)
            out.append({"stem": stem + ("-previous" if previous else ""), "image": vol.get("path") or "",
                        "config_dir": key, "hives": _hives(cfg), "previous": previous,
                        "source": "mount", "root": str(cfg.parent.parent.parent)})
    for base in ("evidence",):
        tree = root / base
        if tree.is_dir():
            for cfg, previous in _find_config_dirs(tree, max_depth=6):
                key = str(cfg)
                if key in seen:
                    continue
                seen.add(key)
                rel = cfg.parent.parent.parent.relative_to(root).as_posix().replace("/", "_")
                out.append({"stem": rel + ("-previous" if previous else ""), "image": "",
                            "config_dir": key, "hives": _hives(cfg), "previous": previous,
                            "source": "tree", "root": str(cfg.parent.parent.parent)})
    return out


# ── reading hives ────────────────────────────────────────────────────────

def _run_recmd(case_dir: Path, hive: str, out_dir: Path, csv_name: str, *, nl: bool) -> dict[str, Any]:
    from core.executor import run_dotnet
    from tools.eztools import EZ, _resolve_ez_dll
    dll = _resolve_ez_dll(f"{EZ}/RECmd/RECmd.dll")
    args = ["-f", hive, "--bn", str(BATCH), "--csv", str(out_dir), "--csvf", csv_name]
    if nl:
        args.append("--nl")
    res = run_dotnet(dll, args, timeout=300, output_dir=str(out_dir))
    res = dict(res or {})
    res["cmd"] = "RECmd " + " ".join(args)
    return res


def _record_call(case_dir: Path, cmd: str, res: dict[str, Any], csv_path: Path) -> Optional[int]:
    """The read is a tool call in the trace, so the ledger credits the hive
    and an observation can cite it."""
    try:
        from core.execution_log import log
        ok = bool(res.get("success")) and csv_path.is_file()
        stdout = str(res.get("stdout") or "")
        # The executor recorded the run already; that call is the one cited.
        cid = res.get("_atlas_call_id") or log.record_tool_call(
            cmd=cmd, success=ok, truncated=False, retries=0,
            exit_code=int(res.get("exit_code") or (0 if ok else 1)),
            stderr=str(res.get("stderr") or "")[:2000], stdout_excerpt=stdout[:4000],
            stdout_file=str(csv_path) if csv_path.is_file() else "")
        try:
            from core.evidence_index import index_output
            if csv_path.is_file():
                index_output(cid, "ez.recmd_hive", csv_path.read_text(encoding="utf-8", errors="replace"),
                             source_path=str(csv_path))
        except Exception:  # noqa: BLE001
            pass
        return cid
    except Exception:  # noqa: BLE001 - an unconfigured log records nothing
        return None


def read_hive(case_dir: str | os.PathLike, hive: str, out_dir: str | os.PathLike, csv_name: str) -> dict[str, Any]:
    """RECmd over one hive with the baseline batch. A dirty hive whose logs
    are missing is refused by RECmd; the read is repeated with ``--nl`` and
    the state says the values may be stale."""
    root, out = Path(case_dir).resolve(), Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    csv_path = out / csv_name
    res = _run_recmd(root, hive, out, csv_name, nl=False)
    console = str(res.get("stdout") or "") + "\n" + str(res.get("stderr") or "")
    state = {"dirty": bool(re.search(r"(?i)\bdirty\b", console)),
             "logs_replayed": bool(re.search(r"(?i)replay", console)) and not re.search(r"(?i)not exist|missing", console),
             "nl_used": False, "console": [l.strip() for l in console.splitlines() if _DIRTY_RE.search(l)][:8]}
    if not csv_path.is_file() and re.search(r"(?i)dirty|transaction log", console):
        res = _run_recmd(root, hive, out, csv_name, nl=True)
        console = str(res.get("stdout") or "") + "\n" + str(res.get("stderr") or "")
        state.update({"dirty": True, "logs_replayed": False, "nl_used": True,
                      "console": state["console"] + [l.strip() for l in console.splitlines() if _DIRTY_RE.search(l)][:4]})
    cid = _record_call(root, res.get("cmd") or "RECmd", res, csv_path)
    rows: list[dict[str, str]] = []
    if csv_path.is_file():
        with open(csv_path, encoding="utf-8-sig", newline="") as fh:
            rows = [r for r in csv.DictReader(fh) if str(r.get("Deleted") or "False").strip().lower() != "true"]
    return {"rows": rows, "call_id": cid, "csv": str(csv_path), "state": state, "ok": bool(res.get("success"))}


def _key_tail(key: str) -> str:
    """The key path without the hive's root key name."""
    parts = key.split("\\")
    return "\\".join(parts[1:]) if len(parts) > 1 else key


def _current_set(rows: list[dict[str, str]]) -> str:
    for r in rows:
        if _key_tail(r.get("KeyPath", "")).casefold() == "select" and r.get("ValueName") == "Current":
            try:
                return f"ControlSet{int(r.get('ValueData') or 1):03d}"
            except ValueError:
                break
    return "ControlSet001"


def _select(rows, key_suffix: str, value_name: Optional[str] = None, *, cs: str = "") -> list[dict[str, str]]:
    suf = key_suffix.casefold()
    out = []
    for r in rows:
        tail = _key_tail(r.get("KeyPath", ""))
        low = tail.casefold()
        if cs and low.startswith("controlset") and not low.startswith(cs.casefold()):
            continue
        if not (low.endswith(suf) or f"{suf}\\" in low + "\\"):
            continue
        if value_name is not None and r.get("ValueName") != value_name:
            continue
        out.append(r)
    return out


def _value(rows, key_suffix: str, value_name: str, *, cs: str = "") -> str:
    hits = _select(rows, key_suffix, value_name, cs=cs)
    return str(hits[0].get("ValueData") or "").strip() if hits else ""


def _epoch(value: str) -> str:
    try:
        n = int(str(value).strip())
        return _dt.datetime.fromtimestamp(n, _dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC") if n > 0 else ""
    except (ValueError, OverflowError, OSError):
        return ""


def _hex_bytes(value: str) -> bytes:
    v = str(value or "").strip()
    if not v:
        return b""
    try:
        return bytes(int(x, 16) for x in re.split(r"[-\s:]+", v) if x)
    except ValueError:
        return b""


def decode_lsa_name(value: str) -> str:
    """PolPrDmN: an LSA_UNICODE_STRING (length, maximum length, then the
    buffer offset: four bytes on a 32-bit host, eight after four bytes of
    padding on a 64-bit one) and the UTF-16LE name behind it. A header
    that does not fit the data decodes to nothing, never to its bytes."""
    raw = _hex_bytes(value)
    if len(raw) < 8:
        return ""
    length, maximum, offset = struct.unpack("<HHI", raw[:8])
    if offset == 0 and len(raw) >= 16:
        offset = struct.unpack("<Q", raw[8:16])[0]
    if offset < 8 or length % 2 or length > maximum or offset + length > len(raw):
        return ""
    try:
        text = raw[offset:offset + length].decode("utf-16-le").strip("\x00").strip()
    except UnicodeDecodeError:
        return ""
    return text if text and all(c.isprintable() for c in text) else ""


def decode_sid(value: str) -> str:
    """PolPrDmS: a binary SID; empty on a workgroup machine."""
    raw = _hex_bytes(value)
    if len(raw) < 8:
        return ""
    rev, count = raw[0], raw[1]
    authority = int.from_bytes(raw[2:8], "big")
    subs = [str(struct.unpack("<I", raw[8 + 4 * i: 12 + 4 * i])[0]) for i in range(count) if 12 + 4 * i <= len(raw)]
    return "-".join(["S", str(rev), str(authority)] + subs)


def _rip(hive: str, plugin: str) -> str:
    try:
        from core.executor import run
        res = run(["rip.pl", "-r", hive, "-p", plugin], timeout=120)
        return str((res or {}).get("stdout") or "")
    except Exception:  # noqa: BLE001
        return ""


_XP_AUDIT_CATEGORIES = ("System", "Logon", "Object Access", "Privilege Use", "Process Tracking",
                        "Policy Change", "Account Management", "Directory Service Access", "Account Logon")
_AUDIT_SETTING = {0: "none", 1: "success", 2: "failure", 3: "success and failure"}


def _nt_version(version: str) -> tuple[int, int]:
    m = re.match(r"\s*(\d+)\.(\d+)", version or "")
    return (int(m.group(1)), int(m.group(2))) if m else (0, 0)


def _audit_policy(security_hive: str, secrows: list[dict[str, str]] = (), version: str = "") -> list[str]:
    """The audit policy. The rip.pl auditpol plugin reads the Windows 7
    and later layout only; on NT 5.x the raw PolAdtEv value is decoded
    here (nine category DWORDs after the first, 0 none, 1 success, 2
    failure, 3 both); any other version is stated as not decoded."""
    major, minor = _nt_version(version)
    if (major, minor) >= (6, 1):
        text = _rip(security_hive, "auditpol") if security_hive else ""
        lines = [l.strip() for l in text.splitlines()
                 if re.match(r"^\s*[A-Za-z][\w /]+:[\w /-]+\s{2,}(?:S/F|S|F|N)\s*$", l)][:60]
        # An absent policy line is never "no auditing": the profile says so.
        return lines or ["audit policy not decoded (the plugin returned no lines)"]
    if major == 5:
        raw = _hex_bytes(_value(secrows, "policy\\poladtev", "(default)"))
        words = struct.unpack(f"<{len(raw) // 4}I", raw[:len(raw) // 4 * 4]) if len(raw) >= 40 else ()
        if len(words) < 10:
            return ["audit policy not decoded (PolAdtEv absent or short)"]
        return [f"Auditing {'enabled' if words[0] else 'disabled'}"] + [
            f"{name}: {_AUDIT_SETTING.get(v, str(v))}" for name, v in zip(_XP_AUDIT_CATEGORIES, words[1:10])]
    return [f"audit policy not decoded for this version ({version or 'unknown'})"]


def _shutdown_time(rows, system_hive: str, cs: str) -> str:
    raw = _value(rows, "control\\windows", "ShutdownTime", cs=cs)
    b = _hex_bytes(raw) if raw and raw != "(Binary data)" else b""
    if len(b) >= 8:
        ft = struct.unpack("<Q", b[:8])[0]
        if ft:
            return (_dt.datetime(1601, 1, 1, tzinfo=_dt.timezone.utc) + _dt.timedelta(microseconds=ft // 10)).strftime("%Y-%m-%d %H:%M:%S UTC")
    m = re.search(r"(?i)ShutdownTime\s*=?\s*([\d-]+\s+[\d:]+)\s*(Z|UTC)?", _rip(system_hive, "shutdown"))
    return f"{m.group(1)} UTC" if m else ""


# ── the profile ──────────────────────────────────────────────────────────

def _profile_from_rows(inst: dict[str, Any], read: dict[str, dict[str, Any]]) -> dict[str, Any]:
    sysrows = read.get("SYSTEM", {}).get("rows") or []
    softrows = read.get("SOFTWARE", {}).get("rows") or []
    samrows = read.get("SAM", {}).get("rows") or []
    secrows = read.get("SECURITY", {}).get("rows") or []
    cs = _current_set(sysrows)
    cv = "windows nt\\currentversion"
    os_part = {
        "product_name": _value(softrows, cv, "ProductName"),
        "current_build": _value(softrows, cv, "CurrentBuild"),
        "current_version": _value(softrows, cv, "CurrentVersion"),
        "csd_version": _value(softrows, cv, "CSDVersion"),
        "edition_id": _value(softrows, cv, "EditionID"),
        "install_date": _epoch(_value(softrows, cv, "InstallDate")),
        "install_date_note": "install of this build; on Windows 10 and later the last feature update",
        "registered_owner": _value(softrows, cv, "RegisteredOwner"),
        "registered_organization": _value(softrows, cv, "RegisteredOrganization"),
        "registered_note": "text typed at setup, not an identity",
    }
    tz_key = "control\\timezoneinformation"
    zone_raw = _value(sysrows, tz_key, "TimeZoneKeyName", cs=cs) or _value(sysrows, tz_key, "StandardName", cs=cs)
    zone_m = _ZONE_NAME_RE.match(zone_raw)
    time_part = {
        "zone": zone_m.group(1) if zone_m else zone_raw,
        "zone_source": "TimeZoneKeyName" if _value(sysrows, tz_key, "TimeZoneKeyName", cs=cs) else "StandardName (XP form)",
        "bias": _value(sysrows, tz_key, "Bias", cs=cs),
        "standard_bias": _value(sysrows, tz_key, "StandardBias", cs=cs),
        "daylight_bias": _value(sysrows, tz_key, "DaylightBias", cs=cs),
        "active_time_bias": _value(sysrows, tz_key, "ActiveTimeBias", cs=cs),
        "daylight_start": _value(sysrows, tz_key, "DaylightStart", cs=cs),
        "standard_start": _value(sysrows, tz_key, "StandardStart", cs=cs),
        "basis": ["NTFS, registry and event log timestamps are UTC",
                  "FAT12/16/32 volumes and setupapi.dev.log carry the local time of the machine that wrote them",
                  "exFAT carries a UTC offset from Vista SP1 writers on",
                  "a removable volume's local time belongs to whichever machine wrote it, never assumed to be this host"],
    }
    pol_name = ""
    pol_sid = ""
    for r in _select(secrows, "policy\\polprdmn"):
        pol_name = decode_lsa_name(r.get("ValueData") or "") or pol_name
    for r in _select(secrows, "policy\\polprdms"):
        pol_sid = decode_sid(r.get("ValueData") or "") or pol_sid
    identity = {
        "computer_name": _value(sysrows, "control\\computername\\computername", "ComputerName", cs=cs),
        "hostname": _value(sysrows, "services\\tcpip\\parameters", "NV Hostname", cs=cs) or _value(sysrows, "services\\tcpip\\parameters", "Hostname", cs=cs),
        "dns_suffix": _value(sysrows, "services\\tcpip\\parameters", "Domain", cs=cs),
        "dns_suffix_note": "DNS suffix only",
        "domain": pol_name, "domain_sid": pol_sid,
        "domain_note": "LSA primary domain: the domain the machine is joined to, or its workgroup name (then without a SID)" if pol_name else "",
    }
    accounts = []
    for r in samrows:
        m = _SAM_USER_RE.search(str(r.get("ValueData") or ""))
        if not m:
            continue
        d = _SAM_DATES_RE.search(str(r.get("ValueData2") or ""))
        accounts.append({"name": m.group(1).strip(), "rid": int(m.group(2)),
                         "created": (d.group(1) or "").strip() if d else "",
                         "last_login": (d.group(2) or "").strip() if d else "",
                         "flags": str(r.get("ValueData3") or "").replace("Account flags:", "").strip()})
    profiles = []
    for r in _select(softrows, "profilelist"):
        m = _PROFILE_RE.search(str(r.get("ValueData") or ""))
        p = re.search(r"ProfileImagePath:\s*(.+)$", str(r.get("ValueData3") or ""))
        if m:
            profiles.append({"sid": m.group(1), "path": (p.group(1).strip() if p else "")})
    interfaces: dict[str, dict[str, str]] = {}
    for r in _select(sysrows, "tcpip\\parameters\\interfaces", cs=cs):
        tail = _key_tail(r.get("KeyPath", ""))
        guid = tail.rsplit("\\", 1)[-1]
        if not guid.startswith("{"):
            continue
        name = r.get("ValueName") or ""
        if name in ("IPAddress", "DhcpIPAddress", "SubnetMask", "DhcpSubnetMask", "DefaultGateway", "DhcpDefaultGateway",
                    "DhcpServer", "EnableDHCP", "LeaseObtainedTime", "LeaseTerminatesTime", "Domain", "DhcpDomain", "NameServer"):
            v = str(r.get("ValueData") or "").strip()
            if name.startswith("Lease"):
                v = _epoch(v)
            if v and v != "0.0.0.0":
                interfaces.setdefault(guid, {})[name] = v
    interfaces = {g: v for g, v in interfaces.items() if any(k in v for k in ("IPAddress", "DhcpIPAddress"))}
    net_profiles = []
    for r in _select(softrows, "networklist\\profiles"):
        if r.get("ValueName") == "ProfileName":
            net_profiles.append({"name": str(r.get("ValueData") or ""), "key": _key_tail(r.get("KeyPath", "")).rsplit("\\", 1)[-1]})
    gateway_macs = [str(r.get("ValueData") or "") for r in _select(softrows, "networklist\\signatures")
                    if r.get("ValueName") == "DefaultGatewayMac" and re.fullmatch(r"[0-9A-Fa-f]{2}([-:][0-9A-Fa-f]{2}){5}", str(r.get("ValueData") or ""))]
    usb: dict[str, dict[str, str]] = {}
    for r in _select(sysrows, "enum\\usbstor", cs=cs):
        found = _usb_entry(r.get("KeyPath", ""))
        if not found:
            continue
        device, serial, note = found
        entry = usb.setdefault(serial, {"device": device, "serial": serial, **({"serial_note": note} if note else {})})
        if r.get("ValueName") == "FriendlyName":
            entry["friendly_name"] = str(r.get("ValueData") or "")
    software = []
    for r in _select(softrows, "currentversion\\uninstall"):
        m = _UNINSTALL_RE.search(str(r.get("ValueData") or ""))
        if not m or not m.group(1).strip():
            continue
        ts = re.search(r"Timestamp:\s*([\d-]+ [\d:]+)", str(r.get("ValueData2") or ""))
        software.append({"name": m.group(1).strip(), "version": m.group(2).strip(), "publisher": m.group(3).strip(),
                         "install_date": (m.group(4) or "").strip(), "key_time": (ts.group(1) if ts else "")})
    security_hive = inst["hives"].get("SECURITY", "")
    system_hive = inst["hives"].get("SYSTEM", "")
    channels = {}
    for r in _select(sysrows, "services\\eventlog", cs=cs):
        tail = _key_tail(r.get("KeyPath", ""))
        seg = tail.split("\\")
        if len(seg) >= 4 and r.get("ValueName") in ("MaxSize", "Retention"):
            channels.setdefault(seg[3], {})[r["ValueName"]] = str(r.get("ValueData") or "")
    settings = {
        "enable_prefetcher": _value(sysrows, "prefetchparameters", "EnablePrefetcher", cs=cs),
        "ntfs_disable_last_access_update": _value(sysrows, "control\\filesystem", "NtfsDisableLastAccessUpdate", cs=cs),
        "event_log_channels": channels,
        "vss_start": _value(sysrows, "services\\vss", "Start", cs=cs),
        "audit_policy": _audit_policy(security_hive, secrows, os_part["current_version"]) if (security_hive or secrows) else [],
        "note": "what an absence of Prefetch, of 4688 events or of last-access times means",
    }
    power = {"last_shutdown": _shutdown_time(sysrows, system_hive, cs) if system_hive else ""}
    hive_state = {h: read[h]["state"] for h in read}
    stale = [h for h, st in hive_state.items() if st.get("dirty") and not st.get("logs_replayed")]
    return {
        "schema_version": "1.0", "installation": inst["stem"], "root": inst["root"], "previous": inst["previous"],
        "source": inst["source"], "image": inst["image"], "control_set": cs,
        "hives": inst["hives"], "calls": {h: read[h].get("call_id") for h in read},
        "os": os_part, "time": time_part, "identity": identity,
        "accounts": accounts, "profiles": profiles,
        "interfaces": [{"guid": g, **v} for g, v in interfaces.items()],
        "network_profiles": net_profiles, "gateway_macs": gateway_macs,
        "gateway_mac_note": "the gateway's address, never the host's",
        "usb": list(usb.values()), "software": software, "power": power, "settings": settings,
        "hive_state": hive_state,
        "confidence": "LIKELY" if stale else "CONFIRMED",
        "stale_note": (f"hives {', '.join(stale)} were dirty and their transaction logs absent; values may be stale"
                       if stale else ""),
        "taken_at": _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def _profile_csv(profile: dict[str, Any]) -> str:
    import io
    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["field", "value", "note", "hive", "call_id"])
    calls = profile.get("calls") or {}
    for part, hive in (("os", "SOFTWARE"), ("time", "SYSTEM"), ("identity", "SYSTEM"), ("power", "SYSTEM"), ("settings", "SYSTEM")):
        for k, v in (profile.get(part) or {}).items():
            if isinstance(v, (str, int)) and v != "" and not k.endswith("_note") and k != "basis":
                w.writerow([f"{part}.{k}", v, (profile.get(part) or {}).get(f"{k}_note", ""), hive, calls.get(hive, "")])
    for a in profile.get("accounts") or []:
        w.writerow(["accounts.local", f"{a['name']} (RID {a['rid']})", f"created {a['created']}; last login {a['last_login']}; {a['flags']}", "SAM", calls.get("SAM", "")])
    for p in profile.get("profiles") or []:
        w.writerow(["accounts.profile", p["sid"], p["path"], "SOFTWARE", calls.get("SOFTWARE", "")])
    for i in profile.get("interfaces") or []:
        w.writerow(["interfaces.adapter", i.get("IPAddress") or i.get("DhcpIPAddress"), json.dumps(i), "SYSTEM", calls.get("SYSTEM", "")])
    for u in profile.get("usb") or []:
        w.writerow(["usb.device", u["serial"], u["device"], "SYSTEM", calls.get("SYSTEM", "")])
    for s in profile.get("software") or []:
        w.writerow(["software.installed", s["name"], f"{s['version']} {s['publisher']} {s['key_time']}".strip(), "SOFTWARE", calls.get("SOFTWARE", "")])
    return out.getvalue()


# ── observations ─────────────────────────────────────────────────────────

def _host_label(case_dir: Path, inst: dict[str, Any], profile: dict[str, Any]) -> str:
    try:
        from core.evidence_links import host_for_image
        if inst.get("image"):
            label = host_for_image(inst["image"], case_dir)
            if label:
                return label
    except Exception:  # noqa: BLE001
        pass
    return profile["identity"].get("computer_name") or inst["stem"]


def _statements(profile: dict[str, Any], where: str) -> list[tuple[str, str, str]]:
    """``(attr, statement, hive)`` for every fact the profile holds."""
    o, t, i, p, s = profile["os"], profile["time"], profile["identity"], profile["power"], profile["settings"]
    out: list[tuple[str, str, str]] = []
    if o["product_name"]:
        build = " ".join(x for x in (o["current_version"], f"build {o['current_build']}" if o["current_build"] else "", o["csd_version"], o["edition_id"]) if x)
        # The statement carries the words a request uses ("operating system"),
        # so the part binds to the reading by the typed test.
        out.append(("os.product", f"The operating system of the installation {where} is {o['product_name']}" + (f" ({build})" if build else "") + ".", "SOFTWARE"))
    if o["install_date"]:
        out.append(("os.install_date", f"The installation {where} was installed on {o['install_date']} ({o['install_date_note']}).", "SOFTWARE"))
    if o["registered_owner"] or o["registered_organization"]:
        who = ", ".join(x for x in (o["registered_owner"], o["registered_organization"]) if x)
        out.append(("os.registered", f"The registered owner of the installation {where} reads {who} ({o['registered_note']}).", "SOFTWARE"))
    if t["zone"]:
        bias = f", bias {t['bias']} minutes" if t["bias"] else ""
        off = _utc_offset(t["active_time_bias"])
        out.append(("time.zone", f"The time zone of the installation {where} is {t['zone']} (" + _zone_offsets(t) + (f"{off} when last written; " if off else "") + f"{t['zone_source']}{bias}, active bias {t['active_time_bias'] or 'unknown'}).", "SYSTEM"))
    if i["computer_name"]:
        out.append(("identity.computer_name", f"The computer name of the installation {where} is {i['computer_name']}.", "SYSTEM"))
    if i["domain"]:
        sid = f" (SID {i['domain_sid']})" if i["domain_sid"] else " (no domain SID: a workgroup machine)"
        out.append(("identity.domain", f"The primary domain of the installation {where} is {i['domain']}{sid}.", "SECURITY"))
    if i["dns_suffix"]:
        out.append(("identity.dns_suffix", f"The DNS suffix of the installation {where} is {i['dns_suffix']} (DNS suffix only, not domain membership).", "SYSTEM"))
    if profile["accounts"]:
        names = "; ".join(f"{a['name']} (RID {a['rid']}, last login {a['last_login'] or 'never'})" for a in profile["accounts"])
        out.append(("accounts.local", f"The local accounts of the installation {where} (local accounts only) are: {names}.", "SAM"))
    if profile["profiles"]:
        names = "; ".join(f"{q['sid']} at {q['path']}" for q in profile["profiles"] if q["path"])
        out.append(("accounts.profiles", f"The profile list of the installation {where} holds: {names}.", "SOFTWARE"))
    if profile["interfaces"]:
        parts = []
        for a in profile["interfaces"]:
            addr = a.get("IPAddress") or a.get("DhcpIPAddress")
            parts.append(f"{addr}" + (f" via DHCP server {a['DhcpServer']}" if a.get("DhcpServer") else "") + (f", gateway {a.get('DefaultGateway') or a.get('DhcpDefaultGateway')}" if (a.get("DefaultGateway") or a.get("DhcpDefaultGateway")) else ""))
        out.append(("interfaces.addresses", f"The network interfaces of the installation {where} were configured with: {'; '.join(parts)}.", "SYSTEM"))
    if profile["network_profiles"]:
        out.append(("interfaces.network_profiles", f"The network profiles of the installation {where} are: {', '.join(n['name'] for n in profile['network_profiles'])}.", "SOFTWARE"))
    if profile["usb"]:
        devs = "; ".join(f"{u['device']} serial {u['serial']}" + (f" ({u['serial_note']})" if u.get("serial_note") else "")
                         for u in profile["usb"])
        out.append(("usb.devices", f"The USB storage devices recorded by the installation {where} are: {devs}.", "SYSTEM"))
    if profile["software"]:
        names = ", ".join(f"{x['name']} {x['version']}".strip() for x in profile["software"][:80])
        out.append(("software.installed", f"The installed software of the installation {where} lists: {names}.", "SOFTWARE"))
    if p["last_shutdown"]:
        out.append(("power.last_shutdown", f"The last clean shutdown of the installation {where} was at {p['last_shutdown']}.", "SYSTEM"))
    if s["enable_prefetcher"] or s["ntfs_disable_last_access_update"]:
        out.append(("settings.artifacts", f"The installation {where} has EnablePrefetcher={s['enable_prefetcher'] or 'unset'} and NtfsDisableLastAccessUpdate={s['ntfs_disable_last_access_update'] or 'unset'} ({s['note']}).", "SYSTEM"))
    if s["audit_policy"]:
        out.append(("settings.audit_policy", f"The audit policy of the installation {where} reads: {'; '.join(s['audit_policy'][:40])}.", "SECURITY"))
    return out


def record_observations(case_dir: str | os.PathLike, inst: dict[str, Any], profile: dict[str, Any]) -> list[str]:
    from core.claim_graph import add_observation, load_graph
    root = Path(case_dir).resolve()
    host = _host_label(root, inst, profile)
    where = f"under {inst['root']}" if inst["source"] == "tree" else f"on {inst['stem'].removesuffix('-previous')}"
    if inst["previous"]:
        where += " (a previous installation, Windows.old)"
    existing = {(n.get("attrs") or {}).get("baseline"): nid for nid, n in (load_graph(root).get("nodes") or {}).items()
                if isinstance(n, dict) and n.get("kind") == "observation" and (n.get("attrs") or {}).get("installation") == inst["stem"]}
    ids: list[str] = []
    calls = profile.get("calls") or {}
    for attr, statement, hive in _statements(profile, where):
        if attr in existing:
            ids.append(existing[attr])
            continue
        cid = calls.get(hive)
        hive_path = inst["hives"].get(hive, "")
        try:
            rel = str(Path(hive_path).resolve().relative_to(root)) if hive_path else ""
        except ValueError:
            rel = hive_path
        r = add_observation(root, statement, confidence=profile["confidence"],
                            evidence=[{"artifact": rel, "locator": attr, "call_id": cid}] if rel else None,
                            host=host, reasoning=profile.get("stale_note") or "system baseline, read from the hive",
                            attrs={"baseline": attr, "installation": inst["stem"], "hive": rel, "call_id": cid})
        if r.get("success"):
            ids.append(r["node_id"])
    return ids


# ── running it ───────────────────────────────────────────────────────────

def _hive_stamp(inst: dict[str, Any]) -> dict[str, float]:
    out = {}
    for h, p in inst["hives"].items():
        try:
            out[h] = os.path.getmtime(p)
        except OSError:
            out[h] = 0.0
    return out


def run_baseline(case_dir: str | os.PathLike) -> dict[str, Any]:
    """Take the baseline of every installation not profiled yet (or whose
    hives changed). Never raises; the result lists what was taken and why
    an installation was not."""
    root = Path(case_dir).resolve()
    out_root = root / OUT_DIR
    summary: dict[str, Any] = {"taken": [], "skipped": [], "errors": []}
    try:
        installs = find_installations(root)
    except Exception as e:  # noqa: BLE001
        summary["errors"].append(f"installation scan failed: {e!r}"[:200])
        return summary
    if not BATCH.is_file():
        summary["errors"].append(f"batch file missing: {BATCH}")
        return summary
    for inst in installs:
        stem = re.sub(r"[^A-Za-z0-9._-]+", "_", inst["stem"])[:80]
        json_path = out_root / f"{stem}.json"
        stamp = _hive_stamp(inst)
        if json_path.is_file():
            try:
                prior = json.loads(json_path.read_text(encoding="utf-8"))
                if prior.get("hive_stamp") == stamp:
                    summary["skipped"].append({"installation": inst["stem"], "why": "already profiled", "path": str(json_path)})
                    continue
            except (OSError, ValueError):
                pass
        if "SYSTEM" not in inst["hives"] or "SOFTWARE" not in inst["hives"]:
            summary["skipped"].append({"installation": inst["stem"], "why": "SYSTEM or SOFTWARE hive absent"})
            continue
        try:
            read = {h: read_hive(root, p, out_root / stem, f"{h}.csv") for h, p in inst["hives"].items()}
            if not (read.get("SYSTEM", {}).get("rows") or read.get("SOFTWARE", {}).get("rows")):
                why = "; ".join(f"{h}: {' '.join(r['state'].get('console') or [])[:120] or 'no rows read'}"
                                for h, r in read.items() if not r.get("rows"))
                summary["skipped"].append({"installation": inst["stem"], "why": f"hives unreadable ({why})"})
                continue
            profile = _profile_from_rows(inst, read)
            profile["hive_stamp"] = stamp
            out_root.mkdir(parents=True, exist_ok=True)
            json_path.write_text(json.dumps(profile, indent=1), encoding="utf-8")
            (out_root / f"{stem}.csv").write_text(_profile_csv(profile), encoding="utf-8")
            profile["observations"] = record_observations(root, inst, profile)
            json_path.write_text(json.dumps(profile, indent=1), encoding="utf-8")
            _register_units(root, out_root / stem, [json_path, out_root / f"{stem}.csv"])
            summary["taken"].append({"installation": inst["stem"], "path": str(json_path),
                                     "observations": len(profile["observations"]), "confidence": profile["confidence"]})
        except Exception as e:  # noqa: BLE001
            summary["errors"].append(f"{inst['stem']}: {e!r}"[:300])
    return summary


def _register_units(root: Path, out_dir: Path, files: list[Path]) -> None:
    """The baseline's own outputs are answered units, not coverage debt."""
    try:
        from core.coverage_ledger import register_derived_outputs
        register_derived_outputs(root, tool_name="baseline",
                                 arguments={"output_dir": str(out_dir)},
                                 result_text=json.dumps({"success": True, "output_dir": str(out_dir),
                                                         "files": [str(f) for f in files]}))
    except Exception:  # noqa: BLE001
        pass


# ── what the others read ─────────────────────────────────────────────────

def profiles(case_dir: str | os.PathLike) -> list[dict[str, Any]]:
    out = []
    folder = Path(case_dir) / OUT_DIR
    for p in sorted(folder.glob("*.json")) if folder.is_dir() else []:
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            if isinstance(data, dict) and data.get("installation"):
                data["_path"] = str(p)
                out.append(data)
        except (OSError, ValueError):
            continue
    return out


def _rel(case_root: Path, prof: dict[str, Any]) -> str:
    try:
        return Path(prof["_path"]).relative_to(case_root).as_posix()
    except ValueError:
        return str(prof["_path"])


def status_line(case_dir: str | os.PathLike, mount_point: str = "", stem: str = "") -> str:
    """For the MOUNTED VOLUMES block: where the baseline is, or why not. The
    stem is matched whole (disk1 is not disk10) and the mount point at a
    path boundary; the current installation is named first, a previous one
    (Windows.old) apart."""
    root = Path(case_dir).resolve()

    def under(prof: dict[str, Any]) -> bool:
        inst = str(prof.get("installation") or "")
        if stem and (inst == stem or (prof.get("previous") and inst.endswith("-previous")
                                      and inst.startswith(stem) and inst[len(stem):len(stem) + 1] in "_-")):
            return True
        if mount_point:
            r, mp = Path(str(prof.get("root") or "")), Path(mount_point)
            return r == mp or mp in r.parents
        return False

    hits = [p for p in profiles(root) if under(p)]
    if not hits:
        return "baseline: not taken (no Windows installation found or hives unreadable)"
    current = [p for p in hits if not p.get("previous")]
    previous = [p for p in hits if p.get("previous")]
    line = "baseline: " + (_rel(root, current[0]) if current else "none for the current installation")
    if previous:
        line += f" (previous installation: {_rel(root, previous[0])})"
    return line


def _signed_bias(bias: Any) -> int | None:
    """A Windows bias in minutes; an unsigned DWORD rendering of a negative
    bias is read back as negative. None when unreadable."""
    try:
        b = int(str(bias).strip())
    except (TypeError, ValueError):
        return None
    return b - 2 ** 32 if b >= 2 ** 31 else b


def _utc_offset(bias: Any) -> str:
    """"UTC-04:00" for a Windows bias of 240 minutes (UTC = local + bias)."""
    b = _signed_bias(bias)
    if b is None:
        return ""
    return f"UTC{'-' if b > 0 else '+'}{abs(b) // 60:02d}:{abs(b) % 60:02d}"


def _zone_offsets(t: dict[str, Any], de: bool = False) -> str:
    """The zone's offsets, both read from its own values: standard time from
    Bias plus StandardBias, daylight saving from Bias plus DaylightBias
    ("standard UTC-05:00, daylight saving UTC-04:00; "). Empty when Bias is
    unreadable; a zone without daylight saving names its standard offset
    only."""
    base = _signed_bias(t.get("bias"))
    if base is None:
        return ""
    std = base + (_signed_bias(t.get("standard_bias")) or 0)
    words = ("Normalzeit", "Sommerzeit") if de else ("standard", "daylight saving")
    text = f"{words[0]} {_utc_offset(std)}"
    daylight = _signed_bias(t.get("daylight_bias"))
    if daylight:
        text += f", {words[1]} {_utc_offset(base + daylight)}"
    return text + "; "


def _stale_text(prof: dict[str, Any], de: bool) -> str:
    if not prof.get("stale_note"):
        return ""
    if not de:
        return f" [{prof['stale_note']}]"
    dirty = [h for h, st in (prof.get("hive_state") or {}).items()
             if isinstance(st, dict) and st.get("dirty") and not st.get("logs_replayed")]
    return (f" [Hives {', '.join(dirty)} waren dirty und ihre Transaktionsprotokolle fehlten; "
            "Werte können veraltet sein]") if dirty else f" [{prof['stale_note']}]"


def prompt_block(case_dir: str | os.PathLike) -> str:
    """The analyst's opening block: the facts per installation, so they are
    read, not re-derived."""
    profs = profiles(case_dir)
    if not profs:
        return ""
    lines = ["# SYSTEM BASELINE (read from the hives; cite the observation, do not re-derive)"]
    for prof in profs:
        o, t, i = prof["os"], prof["time"], prof["identity"]
        off = _utc_offset(t["active_time_bias"])
        head = f"- {prof['installation']}" + (" (previous installation)" if prof.get("previous") else "") + ":"
        facts = [x for x in (
            f"{o['product_name']} {o['current_version']} build {o['current_build']}".strip() if o["product_name"] else "",
            f"installed {o['install_date']} ({o['install_date_note']})" if o["install_date"] else "",
            f"computer name {i['computer_name']}" if i["computer_name"] else "",
            f"domain {i['domain']}" + (f" (SID {i['domain_sid']})" if i["domain_sid"] else " (workgroup)") if i["domain"] else "",
            f"time zone {t['zone']} (" + _zone_offsets(t) + (f"{off} when last written, " if off else "") + f"ActiveTimeBias {t['active_time_bias'] or '?'} min)" if t["zone"] else "",
            f"registered owner {o['registered_owner']} (typed at setup)" if o["registered_owner"] else "",
            "accounts " + ", ".join(f"{a['name']} (RID {a['rid']})" for a in prof["accounts"]) if prof["accounts"] else "",
            "addresses " + ", ".join((a.get("IPAddress") or a.get("DhcpIPAddress") or "") for a in prof["interfaces"]) if prof["interfaces"] else "",
            f"last shutdown {prof['power']['last_shutdown']}" if prof["power"].get("last_shutdown") else "",
            f"USB serials {', '.join(u['serial'] + (' (no serial, generated id)' if u.get('serial_note') else '') for u in prof['usb'][:8])}" if prof["usb"] else "",
        ) if x]
        lines.append(head + " " + "; ".join(facts) + (f" [{prof['stale_note']}]" if prof.get("stale_note") else ""))
        try:
            rel = Path(prof["_path"]).relative_to(Path(case_dir).resolve()).as_posix()
        except ValueError:
            rel = prof["_path"]
        lines.append(f"  profile: {rel} (observations {', '.join(prof.get('observations') or [])})")
    lines.append("Time basis: NTFS, registry and event logs in UTC; FAT volumes and setupapi.dev.log in the writing "
                 "machine's local time; exFAT carries an offset from Vista SP1 on; a removable volume's local time is its writer's.")
    return "\n".join(lines) + "\n"


def report_lines(case_dir: str | os.PathLike, language: str = "en") -> list[str]:
    """The report's System identification bullets under Scope and Evidence."""
    profs = profiles(case_dir)
    if not profs:
        return []
    de = language == "de"
    lines = [("**Systemidentifikation** (aus den Hives gelesen):" if de else "**System identification** (read from the hives):")]
    for prof in profs:
        o, t, i = prof["os"], prof["time"], prof["identity"]
        off = _utc_offset(t["active_time_bias"])
        bits = [b for b in (
            f"{o['product_name']} ({o['current_version']} build {o['current_build']}{', ' + o['csd_version'] if o['csd_version'] else ''})" if o["product_name"] else "",
            (f"installiert {o['install_date']}" if de else f"installed {o['install_date']}") + f" ({o['install_date_note']})" if o["install_date"] else "",
            (f"Rechnername {i['computer_name']}" if de else f"computer name {i['computer_name']}") if i["computer_name"] else "",
            (f"Domäne {i['domain']}" if de else f"domain {i['domain']}") + (f" (SID {i['domain_sid']})" if i["domain_sid"] else (" (Arbeitsgruppe)" if de else " (workgroup)")) if i["domain"] else "",
            (f"Zeitzone {t['zone']}" if de else f"time zone {t['zone']}") + " (" + _zone_offsets(t, de) + (f"{off}{' zuletzt' if de else ' when last written'}, " if off else "") + f"{t['zone_source']}, bias {t['bias'] or '?'}, active {t['active_time_bias'] or '?'})" if t["zone"] else "",
            (f"eingetragener Eigentümer {o['registered_owner']} (bei der Installation eingetippt)" if de else f"registered owner {o['registered_owner']} (typed at setup)") if o["registered_owner"] else "",
            ("Konten " if de else "accounts ") + ", ".join(f"{a['name']} (RID {a['rid']})" for a in prof["accounts"]) if prof["accounts"] else "",
            (f"letztes Herunterfahren {prof['power']['last_shutdown']}" if de else f"last shutdown {prof['power']['last_shutdown']}") if prof["power"].get("last_shutdown") else "",
        ) if b]
        label = ((" (vorherige Installation)" if de else " (previous installation)") if prof.get("previous") else "")
        lines.append(f"- {prof['installation']}{label}: " + "; ".join(bits) + _stale_text(prof, de))
    lines.append(("- Zeitbasis: NTFS, Registry und Ereignisprotokolle in UTC; FAT-Datenträger und setupapi.dev.log in der Ortszeit des schreibenden Rechners; exFAT trägt ab Vista SP1 einen UTC-Versatz; die Ortszeit eines Wechseldatenträgers gehört dem Rechner, der ihn beschrieb."
                  if de else "- Time basis: NTFS, registry and event logs in UTC; FAT volumes and setupapi.dev.log in the writing machine's local time; exFAT carries a UTC offset from Vista SP1 writers on; a removable volume's local time belongs to whichever machine wrote it."))
    return lines
