"""Rebuild the Markdown indexes under brain/indexes/."""

from __future__ import annotations

import argparse
import datetime as dt
from collections import defaultdict
from pathlib import Path

from core.brain import environment, secrets, store

_ENV_STALE_DAYS = 180


def _environment_warnings(note: store.Note) -> list[str]:
    """Hygiene lint for wiki/environments/ baselines — catches direct-edit
    drift that bypassed the approve/new_note guards."""
    warnings: list[str] = []
    client = store.slugify(str(note.meta.get("client") or ""))
    parent = note.path.parent.name
    if not str(note.meta.get("client") or "").strip():
        warnings.append("environment note missing client")
    elif client != parent:
        warnings.append(f"environment client '{client}' does not match its "
                        f"directory '{parent}'")
    last_verified = str(note.meta.get("last_verified") or "").strip()
    if not last_verified:
        warnings.append("environment note missing last_verified")
    else:
        try:
            verified = dt.date.fromisoformat(last_verified[:10])
            age = (dt.date.today() - verified).days
            if age > _ENV_STALE_DAYS:
                warnings.append(f"stale environment baseline (last verified "
                                f"{last_verified}, {age} days ago)")
        except ValueError:
            warnings.append(f"environment last_verified not a date: "
                            f"'{last_verified}'")
    src = str((note.meta.get("source") or {}).get("type") or "")
    if src not in environment.ALLOWED_SOURCES:
        warnings.append(f"environment source.type '{src or '(missing)'}' not "
                        f"allowed (must be one of: "
                        f"{', '.join(environment.ALLOWED_SOURCES)})")
    hits = environment.verdict_hits(note.body)
    if hits:
        warnings.append(f"verdict language in environment note "
                        f"({', '.join(hits)}) — baselines carry facts, not "
                        "judgments")
    return warnings

INDEX_FILES = ("tag-index.md", "topic-index.md", "case-index.md",
               "tool-index.md", "source-index.md", "graph-index.md")


def _line(note: store.Note) -> str:
    updated = note.meta.get("updated", "?")
    return f"- [{note.title}](../{note.rel_path}) — {note.type}, updated {updated}"


def _write_index(root: Path, name: str, sections: dict[str, list[str]],
                 title: str) -> None:
    # No timestamp: output must be deterministic so rebuilding with unchanged
    # notes leaves the committed indexes byte-identical (clean `git status`).
    lines = [f"# {title}", "",
             "_Generated by rebuild_indexes — do not edit._", ""]
    for key in sorted(sections):
        lines.append(f"## {key}")
        lines.append("")
        lines.extend(sorted(set(sections[key])))
        lines.append("")
    (root / "indexes" / name).write_text("\n".join(lines), encoding="utf-8")


def rebuild(include_confidential: bool = False) -> dict:
    root = store.brain_root()
    (root / "indexes").mkdir(exist_ok=True)

    by_tag: dict[str, list[str]] = defaultdict(list)
    by_type: dict[str, list[str]] = defaultdict(list)
    by_case: dict[str, list[str]] = defaultdict(list)
    by_tool: dict[str, list[str]] = defaultdict(list)
    by_source: dict[str, list[str]] = defaultdict(list)
    graph: dict[str, list[str]] = defaultdict(list)

    slugs: set[str] = set()
    linked: set[str] = set()
    warnings: list[str] = []
    indexed = 0
    skipped_secrets = 0

    notes = list(store.iter_notes(include_confidential=include_confidential))
    slugs = {n.slug for n in notes}

    for note in notes:
        hits = secrets.scan_text(note.body) + secrets.scan_text(str(note.meta))
        if hits:
            kinds = ", ".join(sorted({h.pattern for h in hits}))
            warnings.append(f"SECRET-LIKE content in {note.rel_path} ({kinds}) — not indexed")
            skipped_secrets += 1
            continue
        indexed += 1
        line = _line(note)
        by_type[note.type].append(line)
        for tag in note.tags or ["(untagged)"]:
            by_tag[tag].append(line)
        entities = note.meta.get("entities") or {}
        for case in (entities.get("cases") or []):
            by_case[str(case)].append(line)
        for tool in (entities.get("tools") or []):
            by_tool[str(tool)].append(line)
        src = note.meta.get("source") or {}
        by_source[str(src.get("type") or "unknown")].append(line)

        rel = note.related_slugs()
        linked.update(rel)
        if rel:
            linked.add(note.slug)
            graph[note.slug].extend(f"- [[{r}]]" for r in rel)
        for r in rel:
            if r not in slugs:
                warnings.append(f"broken link [[{r}]] in {note.rel_path}")

        for w in note.warnings:
            warnings.append(f"{note.rel_path}: {w}")
        if not note.tags:
            warnings.append(f"{note.rel_path}: missing tags")
        if note.type == "environment":
            for w in _environment_warnings(note):
                warnings.append(f"{note.rel_path}: {w}")

    for note in notes:
        # environment baselines are standalone by design — client-scoped
        # facts rarely wikilink, and Tier D retrieves them by client match.
        if note.slug not in linked and note.type not in (
                "run", "memory_candidate", "environment"):
            warnings.append(f"orphan note (no links in or out): {note.rel_path}")

    _write_index(root, "tag-index.md", by_tag, "Tag Index")
    _write_index(root, "topic-index.md", by_type, "Topic Index (by type)")
    _write_index(root, "case-index.md", by_case, "Case Index")
    _write_index(root, "tool-index.md", by_tool, "Tool Index")
    _write_index(root, "source-index.md", by_source, "Source Index")
    _write_index(root, "graph-index.md", graph, "Graph Index (outgoing links)")

    return {
        "indexed": indexed,
        "skipped_confidential": store.count_confidential() if not include_confidential else 0,
        "skipped_secrets": skipped_secrets,
        "warnings": warnings,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rebuild brain indexes")
    parser.add_argument("--include-confidential", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)
    summary = rebuild(include_confidential=args.include_confidential)
    print("Indexes rebuilt.")
    print(f"Files indexed: {summary['indexed']}")
    print(f"Files skipped confidential: {summary['skipped_confidential']}")
    print(f"Files skipped secret-like: {summary['skipped_secrets']}")
    print(f"Warnings: {len(summary['warnings'])}")
    if args.verbose:
        for w in summary["warnings"]:
            print(f"  ! {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
